# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               OTC's blog
tagline:             '黑嘿嘿'
description:         '猜猜为啥叫OTC?'
url:                 https://frank809.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Frank Liu
  url:               https://
  email:             frank.cd.liu@gmail.com

# Custom vars
version:             1.0.0
