# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               谷达的黑板报
tagline:             '非著名IT从业人员'
description:         ''
url:                 https://frank809.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Frank Liu
  url:               https://
  email:             frank.cd.liu@gmail.com

# Custom vars
version:             1.0.0
